package com.nice.dcm.simlation.core.event;

public enum EventType {
	CONTACT_ARRIVAL, CONTACT_ABANDONED, CONTACT_RULE_CHANGED, AGENT_LOGIN, AGENT_LOGOFF, AGENT_ACTIVITY_CHANGED, AGENT_COMPLETED_CONTACT 
}
