package com.nice.dcm.distribution.parser.rule;

public enum NodeType {
	ROUTINGRULESET, ROUTINGRULEGROUP, ROUTINGRULE, ACTIONRULE, SKILLANDRULE, SKILLRULE, SKILLSETRULE, WAITING, ORDER, OID, AGENT_STATUS
}
