package com.nice.dcm.distribution.rule.parser.node;

public enum NodeType {
	ROUTINGRULESET, ROUTINGRULEGROUP, ROUTINGRULE, ACTIONRULE, 
	SKILL_SET_SELECTOR, 
	SKILL_SELECTOR, 
	SKILL_OR_SELECTOR, 
	WAITING, 
	PRIORITY, ENTITY_IDENTIFIER, 
	QUEUE_STATUS, BINARY_OPERATOR, SQL_OPERATOR, SKILL_LEVEL_CONDITION;
}
