package com.nice.dcm.simulation.distribution.node;

public enum NodeType {
	AGENTOID,
	ROUTINGRULESET, ROUTINGRULEGROUP, ROUTINGRULE, ACTIONRULE, SKILLANDRULE, SKILLRULE, SKILLSETRULE, WAITING, PRIORITY, ENTITY_IDENTIFIER, 
	QUEUE_STATUS, BINARY_OPERATOR, SQL_OPERATOR, CONDITION;
}
